# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=32, unique=True)),
                ('value', models.PositiveIntegerField()),
                ('charge_date', models.DateField(default=datetime.date.today)),
                ('is_paid', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('period', models.PositiveSmallIntegerField(choices=[(0, 'once'), (1, 'daily'), (2, 'monthly'), (3, 'weekly'), (4, 'bi-weekly'), (5, 'yearly')], default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
