# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='split_with',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
