# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standing_order', '0001_initial'),
        ('charge', '0002_charge_split_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='period',
        ),
        migrations.AddField(
            model_name='charge',
            name='standing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standing_order.StandingOrder'),
        ),
    ]
