# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charge', '0003_auto_20171003_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charge',
            name='split_with',
            field=models.ManyToManyField(related_name='charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
