# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0004_auto_20171004_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='uid',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
    ]
