# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0005_auto_20171004_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
