# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('period', models.PositiveSmallIntegerField(choices=[(0, 'daily'), (1, 'weekly'), (2, 'bi-weekly'), (3, 'monthly'), (4, 'yearly')], default=3)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('split_with', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
